### PR TITLE
Prevent exception if default controls are restricted

### LINKED ISSUE #94: Multiblock conflict with block manager
If multiblock has its configuration options restricted by tool_blockmanager, it can result in an exception:
```
Exception - Argument 1 passed to block_multiblock\icon_helper::delete() must be of the type string, null given, called in [dirroot]/blocks/multiblock/block_multiblock.php on line 245
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 107 of /blocks/multiblock/classes/icon_helper.php: TypeError thrown
    line 245 of /blocks/multiblock/block_multiblock.php: call to block_multiblock\icon_helper::delete()
    line 1181 of /lib/blocklib.php: call to block_multiblock->get_content_for_output()
    line 1239 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 374 of /lib/blocklib.php: call to block_manager->ensure_content_created()
    line 4004 of /lib/outputrenderers.php: call to block_manager->region_has_content()
    line 40 of /theme/boost/layout/columns2.php: call to core_renderer->blocks()
    line 1401 of /lib/outputrenderers.php: call to include()
    line 1331 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 245 of /course/view.php: call to core_renderer->header()
```

This is because `$str` is defined in a loop that runs for each default control. If these controls are disabled by blockmanager, `$str` is never set before being used to by the additional "Split or delete multiblock" control.

### PR DESCRIPTION
**Pull request by marxjohnson**
Fixes #94.

### CODE REVIEW

**Comment by catalyst-eu** [comment]
Approved by Anton S (haven't got write access to do it properly)

**Comment by danmarsden** [comment]
@catalyst-eu - I've just sent an invite to that account to be added to the EU group in the catalyst org repo (I assume that is a generic account rather than one "owned" by Anton? - (hopefully?) - I can't see a separate "real" account for Anton in github but ping me internally and I can add that too...

**Comment by danmarsden** [comment]
also - the github action pipelines on this repo were green before this patch, so we really need to fix the errors that it's now reporting before we merge in new changes... even though they don't look related, they look to be mostly an easy fix.

**Comment by marxjohnson** [comment]
Hi Dan,
It looks like they're mostly codechecker violations for MOODLE_INTERNAL checks that are no longer required, on files that I'm not otherwise touching. Good to get them fixed though, so remove them in a separate commit.

**Comment by marxjohnson** [comment]
@danmarsden I have resolved those codechecker issues. The remaining CI failures are due to deprecated behat steps in Moodle 4.0+. I can't fix that as part of this PR as we will need to create new stable branch for <=3.11. I have created #96 to address it once this PR is merged.

**Comment by marxjohnson** [comment]
Doh, ignore that. I must have based my branch on an older version of master. I rebased because it was conflicting and now I'm getting green across the board. I'll merge this in now.

**Comment by danmarsden** [comment]
that makes more sense! - I was getting confused by the errors it was reporting myself too!! - :-)

**Pull request merged**
